### PR TITLE
Issue 33601: **R Script export should export using ImmunespaceR (not …

### PR DESCRIPTION
**Pull request by cnathe**
…Rlabkey) when immport module is enabled in that container

### CODE REVIEW

**Comment by cnathe** [comment]
Yes @ldash that is correct. Here is the full logic for when to use the ImmuneSpaceR export script:

1. the container must be of folder type Dataspace OR study
2. the immport module must be enabled in that container
3. the query must be a study dataset
4. the view must be a supported view name, either the default or "full" (i.e. see issue 29755)

**Comment by ldash** [comment]
@cnathe is there limitation on the query name as well?
@juyeongkim , @ehfhcrc what are the limitations on the dataset names that we have?

**Comment by cnathe** [comment]
@ldash I'm not sure what you mean by "limitation on the query name". Item #3 in the logic that I mentioned will check that the query that is being viewed is from the study schema and matches a study dataset.

**Comment by ldash** [comment]
@cnathe Cory, here is the full answer...
We rely on this query to pull in the allowed datasets:
https://github.com/RGLab/ImmuneSpaceR/blob/dev/R/ISCon-dataset.R#L125
The source code of which is this:
https://test.immunespace.org/query/Studies/viewQuerySource.view?schemaName=study&query.queryName=ISC_study_datasets
So only the available datasets, which are non-empty and are not hidden, show up.
The query also is actually dynamic: it is filtered by the "Data Finder"!
It's best if you could only enable ImmuneSpaceR export for the current results of this query, because if an input dataset is specified, which is not in that query (i.e. the dataset is empty), then ImmuneSpaceR will throw an error and not even return an empty dataset / data.frame ...
I guess, you could also just enumerate the complete set (since we try to hide the empty ones):
https://test.immunespace.org/query/Studies/executeQuery.view?schemaName=study&query.queryName=ISC_study_datasets

@juyeongkim does this sound right to you?

**Comment by juyeongkim** [comment]
@ldash yep. I would just use `ISC_study_datasets` to be consistent.

**Comment by cnathe** [comment]
OK. Thank you guys for the clarification. So right now the logic would allow for the ImmuneSpaceR export for any dataset listed here:
https://test.immunespace.org/study/Studies/manageTypes.view?
but it sounds like ideally, we would instead rather only allow it for those datasets listed in that ISC_study_datasets query:
https://test.immunespace.org/query/Studies/executeQuery.view?schemaName=study&query.queryName=ISC_study_datasets&query.sort=Name

My suggestion is that since this pull request is about changing the logic for the folder type (which sounds like it still applies), we merge that change and then you guys can talk to Matt and Angelica about prioritizing or getting an issue opened about this study dataset list filtering change.

**Comment by ldash** [comment]
@cnathe ok, go ahead and merge then. We will meanwhile adjust ImmuneSpaceR on our side to allow for empty datasets, so that things don't break...

**Pull request merged**
